/** @type {import('../tokens.contract').ThemeContract} */
export const productALightTheme = {
  name: 'product-a',
  mode: 'light',
  primitives: {
    color: {
      slate50: '#f8fafc',
      slate100: '#f1f5f9',
      slate200: '#e2e8f0',
      slate300: '#cbd5e1',
      slate400: '#94a3b8',
      slate500: '#64748b',
      slate600: '#475569',
      slate700: '#334155',
      slate800: '#1e293b',
      slate900: '#0f172a',
      slate950: '#020617',
      blue50: '#eff6ff',
      blue100: '#dbeafe',
      blue500: '#3b82f6',
      blue600: '#2563eb',
      blue700: '#1d4ed8',
      red500: '#ef4444',
      amber500: '#f59e0b',
      emerald500: '#10b981',
      white: '#ffffff',
      black: '#000000',
    },
    space: {
      0: '0px',
      px: '1px',
      1: '0.25rem', // 4px
      2: '0.5rem', // 8px
      3: '0.75rem', // 12px
      4: '1rem', // 16px
      6: '1.5rem', // 24px
      8: '2rem', // 32px
      12: '3rem', // 48px
    },
    radius: {
      none: '0px',
      sm: '0.25rem',
      md: '0.5rem',
      lg: '0.75rem',
      full: '9999px',
    },
    typography: {
      fontSans: 'Inter, system-ui, -apple-system, sans-serif',
      fontMono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
      sizeXs: 'clamp(0.75rem, 0.7rem + 0.25vw, 0.875rem)',
      sizeSm: 'clamp(0.875rem, 0.8rem + 0.38vw, 1rem)',
      sizeMd: 'clamp(1rem, 0.95rem + 0.25vw, 1.125rem)',
      sizeLg: 'clamp(1.125rem, 1.05rem + 0.38vw, 1.25rem)',
      sizeXl: 'clamp(1.25rem, 1.15rem + 0.5vw, 1.5rem)',
      sizeXl2: 'clamp(1.5rem, 1.3rem + 1vw, 2rem)',
    },
    shadow: {
      sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
      lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    },
  },
  color: {
    backgroundPrimary: 'var(--vami-primitive-color-white)',
    backgroundSecondary: 'var(--vami-primitive-color-slate50)',
    backgroundSubdued: 'var(--vami-primitive-color-slate100)',
    surfaceCard: 'var(--vami-primitive-color-white)',
    surfaceElevated: 'var(--vami-primitive-color-white)',
    textPrimary: 'var(--vami-primitive-color-slate900)',
    textSecondary: 'var(--vami-primitive-color-slate600)',
    textSubtle: 'var(--vami-primitive-color-slate500)',
    borderSubtle: 'var(--vami-primitive-color-slate200)',
    borderStrong: 'var(--vami-primitive-color-slate300)',
    brandAccent: 'var(--vami-primitive-color-blue600)',
    brandHover: 'var(--vami-primitive-color-blue700)',
    danger: 'var(--vami-primitive-color-red500)',
    success: 'var(--vami-primitive-color-emerald500)',
    warning: 'var(--vami-primitive-color-amber500)',
  },
  spacing: {
    xs: 'var(--vami-primitive-space-1)',
    sm: 'var(--vami-primitive-space-2)',
    md: 'var(--vami-primitive-space-4)',
    lg: 'var(--vami-primitive-space-6)',
    xl: 'var(--vami-primitive-space-8)',
    xl2: 'var(--vami-primitive-space-12)',
  },
  radius: {
    none: 'var(--vami-primitive-radius-none)',
    sm: 'var(--vami-primitive-radius-sm)',
    md: 'var(--vami-primitive-radius-md)',
    lg: 'var(--vami-primitive-radius-lg)',
    full: 'var(--vami-primitive-radius-full)',
  },
  breakpoint: {
    xs: '0px',
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    xl2: '1536px',
  },
  typography: {
    fontSans: 'var(--vami-primitive-typography-font-sans)',
    fontMono: 'var(--vami-primitive-typography-font-mono)',
    sizeXs: 'var(--vami-primitive-typography-size-xs)',
    sizeSm: 'var(--vami-primitive-typography-size-sm)',
    sizeMd: 'var(--vami-primitive-typography-size-md)',
    sizeLg: 'var(--vami-primitive-typography-size-lg)',
    sizeXl: 'var(--vami-primitive-typography-size-xl)',
    sizeXl2: 'var(--vami-primitive-typography-size-xl2)',
  },
  shadow: {
    sm: 'var(--vami-primitive-shadow-sm)',
    md: 'var(--vami-primitive-shadow-md)',
    lg: 'var(--vami-primitive-shadow-lg)',
  },
};
