packages:
  - 'apps/*'
  - 'services/*'
  - 'libs/**'

allowBuilds:
  argon2: true
  esbuild: true
  nx: true

minimumReleaseAgeExclude:
  - react-router-dom@7.18.2
  - react-router@7.18.2

overrides:
  axios: '^1.18.0'
  brace-expansion: '^5.0.8'
  react-router: '7.18.2'
  turbo-stream: '^3.0.0'
