/**
 * Blog Module — Model (canonical Mongoose schema)
 * Moved from models/BlogPost.js — single source of truth for the blog domain.
 *
 * Content field uses a triple projection pattern:
 *
 * 1. lexicalState (Object)  — Lexical JSON state; SOURCE OF TRUTH.
 *    Re-loaded into the editor on edit. Never derived from HTML.
 *
 * 2. html (String)          — DOMPurify-sanitized HTML projection.
 *    Used for public rendering via RichTextRenderer (Server Component).
 *    Generated by $generateHtmlFromNodes on the client, sanitized server-side.
 *
 * 3. plainText (String)     — Plain text projection, select:false.
 *    Used for Atlas Search, SEO meta description fallback, and AI processing.
 *    Never sent to the client by default (must be explicitly selected).
 */
import mongoose from 'mongoose';

const BlogPostSchema = new mongoose.Schema(
  {
    title: { type: String, required: true, trim: true },
    slug: { type: String, required: true, unique: true, trim: true },
    coverImage: { type: String },

    // ─── Lexical RTE content (triple projection) ─────────────────────────
    content: {
      // Lexical JSON state — the editor's source of truth
      lexicalState: {
        type: Object,
        required: true,
      },
      // Sanitized HTML — for public rendering, never stored raw from client
      html: {
        type: String,
        default: '',
      },
      // Plain text extraction — for search and SEO, excluded from default queries
      plainText: {
        type: String,
        default: '',
        select: false,
      },
    },

    excerpt: { type: String, trim: true },
    tags: [{ type: String, trim: true }],
    status: {
      type: String,
      enum: ['draft', 'published'],
      default: 'draft',
    },
    seoTitle: { type: String, trim: true },
    seoDescription: { type: String, trim: true },
    publishedAt: { type: Date },
  },
  { timestamps: true }
);

// ─── Indexes ─────────────────────────────────────────────────────────────────
BlogPostSchema.index({ status: 1, publishedAt: -1 });
BlogPostSchema.index({ slug: 1 }, { unique: true });

export default mongoose.models.BlogPost || mongoose.model('BlogPost', BlogPostSchema);
