api:
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
